#!/usr/bin/env node
// Reads .env and writes src/environments/environment.ts
// Run automatically via prestart / prebuild hooks.
const fs = require('fs');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const mapboxToken   = process.env['MAPBOX_TOKEN'] || '';
const supabaseUrl   = process.env['NEXT_PUBLIC_SUPABASE_URL'] || '';
const supabaseKey   = process.env['NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'] || '';

if (!mapboxToken)  console.warn('[sync-env] Warning: MAPBOX_TOKEN is missing in .env');
if (!supabaseUrl)  console.warn('[sync-env] Warning: NEXT_PUBLIC_SUPABASE_URL is missing in .env');
if (!supabaseKey)  console.warn('[sync-env] Warning: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY is missing in .env');

const content = `// Auto-generated by scripts/sync-env.js — do not edit manually.
// Edit .env and restart the dev server to update.
export const environment = {
  mapboxToken: '${mapboxToken}',
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');
console.log('[sync-env] environment.ts generated ✔');
